source_repo_url: "https://github.com/devRonPark/full-stack-fastapi-template.git"
source_branch: "master"
source_credential_id: "github-source-credential"
source_access_token_env: "K8S_DEPLOY_AGENT_SOURCE_TOKEN"

gitops_repo_url: "https://github.com/devRonPark/k8s-deploy-agent-demo-gitops.git"
gitops_branch: "main"
gitops_path: "."
gitops_credential_id: "github-gitops-credential"

app_name: "fastapi-demo"
environment: "dev"
target_namespace: ""
